# never use this in production!!!!!
spring:
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:mydb
    username: warehouse_dbo
    password: warehouse
    driverClassName: org.h2.Driver

server:
  servlet:
    context-path: /
  port: 8090