# never use this in production!!!!!
spring:
  jpa:
    open-in-view: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:mydb
    username: application_dbo
    password: application
    driverClassName: org.h2.Driver

springdoc:
  api-docs:
    path: /api/openapi
  swagger-ui:
    path: /api/swagger-ui

googlemaps:
  apikey: ""
  language: "de-DE"

redis:
  hostname: 127.0.0.1
  port: 6379

server:
  servlet:
    context-path: /
  port: 8088