spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: calculator
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/api/tax, /api/tax-with-rate
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: import
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/import-products

        - id: api
          uri: http://127.0.0.1:8088
          predicates:
            - Path=/api/**


server:
  port: 8080
