spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: calculator
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/api/tax, /api/tax-with-rate
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: api
          uri: http://127.0.0.1:8088
          predicates:
            - Path=/api/**

        - id: frontend
          uri: http://127.0.0.1:4200
          predicates:
            - Path=/**

server:
  port: 80
